# .github/workflows/sync-upstream-main.yml
name: Sync Upstream Releases

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -B upstream-sync

    - name: Add Upstream Remote
      run: git remote add upstream https://github.com/cosmos/interchain-security.git

    - name: Fetch and merge upstream
      run: |
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories --no-edit || true
    
#    - name: Remove workflow files
#      run: |
#        git rm -r --cached .github/workflows/ || echo "No workflow files to remove"
#        git commit -m "Remove workflow files after sync" || echo "No changes to commit"

    - name: Push changes and tags using GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin upstream-sync
        git push origin --tags

