name: Sync Main Branch

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: 'main'
        token: ${{ secrets.actions-user }}

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config --global credential.helper store

    - name: Add Upstream Remote
      run: git remote add upstream https://github.com/cosmos/interchain-security.git

    - name: Fetch Upstream
      run: git fetch upstream

    - name: Sync Main Branch
      run: |
        git checkout main
        git merge upstream/main --allow-unrelated-histories || true

    - name: Disable Unnecessary Workflows
      run: |
        # Get the list of all workflow files
        workflows=$(ls .github/workflows/*.yml)

        # List of workflows to keep
        keep_workflows=("sync-upstream-main.yml" "sync-upstream-releases.yml")

        # Disable all workflows except the specified ones
        for workflow in $workflows; do
          filename=$(basename $workflow)
          if [[ ! " ${keep_workflows[@]} " =~ " ${filename} " ]]; then
            echo "Disabling $filename"
            sed -i '1s/^/#/' $workflow
            sed -i '2s/^/#/' $workflow
          fi
        done

        git add .github/workflows/*.yml
        git commit -m "Disable unnecessary workflows"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.actions-user }}
      run: |
        git remote set-url origin https://${{ secrets.actions-user }}@github.com/clemensgg/interchain-security.git
        git push https://${{ secrets.actions-user }}@github.com/clemensgg/interchain-security.git main
