# .github/workflows/sync-upstream-main.yml
name: Sync Upstream Releases

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -B upstream-sync

    - name: Add Upstream Remote
      run: git remote add upstream https://github.com/cosmos/interchain-security.git

    - name: Fetch and merge upstream
      run: |
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories --no-edit || true

    - name: Pull latest changes from origin before pushing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/clemensgg/interchain-security.git
        git pull origin upstream-sync --rebase

    - name: Push changes and tags using GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin upstream-sync
        git push origin --tags
